# This file is automatically generated by https://github.com/heroku/cli/blob/main/scripts/release/homebrew.js
# Do not update this file directly;
# Please update the template instead:
# https://github.com/heroku/cli/blob/main/scripts/release/homebrew/templates/heroku.rb
class Heroku < Formula
  desc "Everything you need to get started with Heroku"
  homepage "https://cli.heroku.com"
  url "https://cli-assets.heroku.com/versions/11.0.1/840e377/heroku-v11.0.1-840e377-darwin-x64.tar.xz"
  sha256 "ab69a5e6c9ba95a83cc1b02f337c0028b6619fe3816c171426306af616e57b5b"
  version "11.0.1"
  version_scheme 1

  on_macos do
    on_arm do
      url "https://cli-assets.heroku.com/versions/11.0.1/840e377/heroku-v11.0.1-840e377-darwin-arm64.tar.xz"
      sha256 "8fb09274fbb4ddb725430dec542edddba6e59cc6650b9a60b166011d13f01e3e"
    end
  end

  on_linux do
    on_intel do
      url "https://cli-assets.heroku.com/versions/11.0.1/840e377/heroku-v11.0.1-840e377-linux-x64.tar.xz"
      sha256 "86a5b42e6db07d760e890d9a3aa81502dd2af0171c5abfa3589b6e130b38421f"
    end
    on_arm do
      url "https://cli-assets.heroku.com/versions/11.0.1/840e377/heroku-v11.0.1-840e377-linux-arm.tar.xz"
      sha256 "0648e18a6c71979121e82762610cbb83185aa4989e06db33dd83129de96d1d14"
    end
  end

  def install
    inreplace "bin/heroku", /^CLIENT_HOME=/, "export HEROKU_OCLIF_CLIENT_HOME=#{lib/"client"}\nCLIENT_HOME="
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/heroku"

    bash_completion.install libexec/"autocomplete-scripts/brew/bash" => "heroku"
    zsh_completion.install libexec/"autocomplete-scripts/brew/zsh/_heroku"
  end

  def caveats; <<~EOS
    To use the Heroku CLI's autocomplete --
      Via homebrew's shell completion:
        1) Follow homebrew's install instructions https://docs.brew.sh/Shell-Completion
            NOTE: For zsh, as the instructions mention, be sure compinit is autoloaded
                  and called, either explicitly or via a framework like oh-my-zsh.
        2) Then run
          $ heroku autocomplete --refresh-cache
      OR
      Use our standalone setup:
        1) Run and follow the install steps:
          $ heroku autocomplete
  EOS
  end

  test do
    system bin/"heroku", "version"
  end
end
