# This file is automatically generated by https://github.com/heroku/cli/blob/main/scripts/release/homebrew.js
# Do not update this file directly;
# Please update the template instead:
# https://github.com/heroku/cli/blob/main/scripts/release/homebrew/templates/heroku.rb
class Heroku < Formula
  desc "Everything you need to get started with Heroku"
  homepage "https://cli.heroku.com"
  url "https://cli-assets.heroku.com/versions/10.14.0/c0d7800/heroku-v10.14.0-c0d7800-darwin-x64.tar.xz"
  sha256 "fe23394a3e4a57634a9aee3d36b9d8c0e9a81c490f4b0cdba67dd7114d4c5579"
  version "10.14.0"
  version_scheme 1

  on_macos do
    on_arm do
      url "https://cli-assets.heroku.com/versions/10.14.0/c0d7800/heroku-v10.14.0-c0d7800-darwin-arm64.tar.xz"
      sha256 "b67c48cd042e241f175ec56aa9fd269c74c80b88145acea2e9a7f9e1cd114181"
    end
  end

  on_linux do
    on_intel do
      url "https://cli-assets.heroku.com/versions/10.14.0/c0d7800/heroku-v10.14.0-c0d7800-linux-x64.tar.xz"
      sha256 "caf15a93faaff1bb5220d557269ef447b8c22d7e73495be28ae495237331afa7"
    end
    on_arm do
      url "https://cli-assets.heroku.com/versions/10.14.0/c0d7800/heroku-v10.14.0-c0d7800-linux-arm.tar.xz"
      sha256 "5de948c4794ad7d7abdae4e7d9089caa05da19e1756e63ab51982766874504e1"
    end
  end

  def install
    inreplace "bin/heroku", /^CLIENT_HOME=/, "export HEROKU_OCLIF_CLIENT_HOME=#{lib/"client"}\nCLIENT_HOME="
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/heroku"

    bash_completion.install libexec/"autocomplete-scripts/brew/bash" => "heroku"
    zsh_completion.install libexec/"autocomplete-scripts/brew/zsh/_heroku"
  end

  def caveats; <<~EOS
    To use the Heroku CLI's autocomplete --
      Via homebrew's shell completion:
        1) Follow homebrew's install instructions https://docs.brew.sh/Shell-Completion
            NOTE: For zsh, as the instructions mention, be sure compinit is autoloaded
                  and called, either explicitly or via a framework like oh-my-zsh.
        2) Then run
          $ heroku autocomplete --refresh-cache
      OR
      Use our standalone setup:
        1) Run and follow the install steps:
          $ heroku autocomplete
  EOS
  end

  test do
    system bin/"heroku", "version"
  end
end
