# This file is automatically generated by https://github.com/heroku/cli/blob/main/scripts/release/homebrew.js
# Do not update this file directly;
# Please update the template instead:
# https://github.com/heroku/cli/blob/main/scripts/release/homebrew/templates/heroku.rb
class Heroku < Formula
  desc "Everything you need to get started with Heroku"
  homepage "https://cli.heroku.com"
  url "https://cli-assets.heroku.com/versions/11.1.1/cf27509/heroku-v11.1.1-cf27509-darwin-x64.tar.xz"
  sha256 "f905b7ace442517bb0eeefaa71009396e65d96a7371596e9abd37df4abc8deb3"
  version "11.1.1"
  version_scheme 1

  on_macos do
    on_arm do
      url "https://cli-assets.heroku.com/versions/11.1.1/cf27509/heroku-v11.1.1-cf27509-darwin-arm64.tar.xz"
      sha256 "2f54da2aedeec88c3b4a457984b95b056b60781adb57efb2487133c25d4a8bce"
    end
  end

  on_linux do
    on_intel do
      url "https://cli-assets.heroku.com/versions/11.1.1/cf27509/heroku-v11.1.1-cf27509-linux-x64.tar.xz"
      sha256 "ac36638304bef7d16eb36d8157aa8376b3411eb1abfa6063dc40240e6cf8fccf"
    end
    on_arm do
      url "https://cli-assets.heroku.com/versions/11.1.1/cf27509/heroku-v11.1.1-cf27509-linux-arm.tar.xz"
      sha256 "799ae3b08133aa1c0d66d20e9951e491d8030d980e4a950959d7a97fc991f73b"
    end
  end

  def install
    inreplace "bin/heroku", /^CLIENT_HOME=/, "export HEROKU_OCLIF_CLIENT_HOME=#{lib/"client"}\nCLIENT_HOME="
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/heroku"

    bash_completion.install libexec/"autocomplete-scripts/brew/bash" => "heroku"
    zsh_completion.install libexec/"autocomplete-scripts/brew/zsh/_heroku"
  end

  def caveats; <<~EOS
    To use the Heroku CLI's autocomplete --
      Via homebrew's shell completion:
        1) Follow homebrew's install instructions https://docs.brew.sh/Shell-Completion
            NOTE: For zsh, as the instructions mention, be sure compinit is autoloaded
                  and called, either explicitly or via a framework like oh-my-zsh.
        2) Then run
          $ heroku autocomplete --refresh-cache
      OR
      Use our standalone setup:
        1) Run and follow the install steps:
          $ heroku autocomplete
  EOS
  end

  test do
    system bin/"heroku", "version"
  end
end
