name: Node CI Suite

on:
  push

jobs:
  test:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - run: brew update
      - run: brew cleanup
      - run: ./scripts/test
